// <auto-generated />
namespace valorantProject.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mig_newColumnMaps_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mig_newColumnMaps_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202209221240439_mig_newColumnMaps_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
